### ISSUE TITLE
Is light source moving?

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/education-tool#18]
![image](https://github.com/skejeton/education-tool/assets/52492460/501b17e8-7523-40ea-bbd9-ca4d718ba447)
![image](https://github.com/skejeton/education-tool/assets/52492460/fdd09574-746c-4405-8f34-7e51c5dc21b5)
![image](https://github.com/skejeton/education-tool/assets/52492460/9ab818f6-0f7f-4bc1-b4fc-df6cf975a069)

**Comment by skejeton** [comment]
No, it's a static directional light.

**Comment by vtereshkov** [comment]
Something unnatural is happening with shadows (see the screenshots I attached). I cannot imagine any fixed light source that could have produced such shadows. For example, if the light source is fixed, the bottom right (w.r.t. the observer) face of the wall should be either always lit, or always shaded.

**Comment by skejeton** [comment]
I think you're right, what's likely happening is that the shadow calculations ignore camera rotation.

**Comment by skejeton** [comment]
Ok, it was a misunderstanding. The light source may appear to be moving if you see it as the castle rotating, but in reality the camera is rotating around the castle.
