### ISSUE TITLE
Cannot run release builds: DLLs missing

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/education-tool#2]
![image](https://github.com/skejeton/education-tool/assets/52492460/a5467c2a-fdfd-4937-a8ea-27c0b9b0f169)
![image](https://github.com/skejeton/education-tool/assets/52492460/c3a68e95-383d-43cd-859b-126c9782ad60)
![image](https://github.com/skejeton/education-tool/assets/52492460/4251c57d-75b3-4cc0-a648-3a920ef749fb)
![image](https://github.com/skejeton/education-tool/assets/52492460/985200b0-c32c-4eb2-a8f7-167b26f85eb7)

**Comment by skejeton** [comment]
I'm looking into it rn

**Comment by skejeton** [comment]
Does this help: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
?

**Comment by vtereshkov** [comment]
@skejeton No, it doesn't, as I have already told you. My conjecture is that this *.exe is in fact a debug build rather than a release one, so that it expects the debug versions of those DLLs (notice the D suffix in the DLL names).

On the other hand, when I run the same *.exe on another machine with Visual Studio installed, it no more complains about the DLLs, but immediately crashes on a failed assertion:

![image](https://github.com/skejeton/education-tool/assets/52492460/90795bd6-bb00-4b65-a0e1-ae5bf9cc9e07)

**Comment by vtereshkov** [comment]
@skejeton The only way to run the app I have found so far is to clone the repo and rebuild everything from scratch:

![image](https://github.com/skejeton/education-tool/assets/52492460/c856913c-4cff-4d6a-ae40-48e1a645bd27)

**Comment by vtereshkov** [comment]
@skejeton I have finally figured out what we need to fix this issue:

- Publish release builds of `catedu.exe` rather than debug ones (no more problems with missing DLLs)
- Put the `user` and `assets` folders to the same folder as `catedu.exe` (they all can be in the same archive)

**Comment by skejeton** [comment]
Hmm interesting because I thought the builds were already compiled in release mode. I'll fix the CI right now.

**Comment by skejeton** [comment]
Yes indeed the build script used debug builds.

**Comment by skejeton** [comment]
@vtereshkov Can you confirm the CI builds work with the most recent build?

**Comment by vtereshkov** [comment]
@skejeton Your latest Git LFS fix CI has failed -- please check it. Without this fix, I only have symlinks, not the actual assets.

**Comment by skejeton** [comment]
Yeah I saw that. I'm working on it right now.

**Comment by skejeton** [comment]
@vtereshkov Should be all fixed.

**Comment by vtereshkov** [comment]
@skejeton Confirmed and closed.
