### ISSUE TITLE
Improve object selection

### ISSUE THREAD

**Issue by skejeton** [skejeton/education-tool#26]
- [x] The select button opens properties but doesn't close them
- [x] The select button should be moved just to the object entry
- [x] Selecting objects in the world

**Comment by matejovic** [comment]
agree that the select button should be the whole row (the part that gets highlighted when it's selected) it would benefit from a hover effect as well as the buttons have. 

(agreed) When I click on an object in space, I want to open its editable detail window.

More
- Removing ground, middle, lexi and backdrop will result in irreversibly broken editor state. That should not be possible. Even if reversal is possible, delete should always require confirmation or be reversible (such as we won't hard delete right away)
- Move existing objects around
- show shadow of the objects when in selection.
- add more configuration to objects. For example adjust colors / textures of floor tiles. Maybe we should have only single floor tile with various options. 
- allow me to define dimensions of objects, such as floor is 4x4 and pavement 1x20

**Comment by skejeton** [comment]
Moved this to separate issues except for the last one, what do you mean?

**Comment by matejovic** [comment]
In the editor some tiles can be preconfigured before placing to extend
dimensions (such as the magic hand will drop the whole area at once
according to dimensions input.

This same feature could be used for scripting - such as I place objects and
tiles in position and connect it to the language layer.
