### ISSUE TITLE
UX/UI: Entity/tilemap input method inconsistency

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/education-tool#43]
For tilemaps, I select the tile type from a menu. For entities, I have to look at the quick reference card and manually enter one of the supported entity type names. For consistency and convenience, there should be a menu too.

**Comment by skejeton** [comment]
I think at this point it'd be good to have a drop-down menu 
- [ ] #46

**Comment by skejeton** [comment]
Not anymore.
