### ISSUE TITLE
UX/UI: No OK, Cancel, Close buttons

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/education-tool#44]
Without the customary controls, even the simplest tasks become hard:
* How to confirm entering a new entity?
* How to close the entity properties window? Will my changes be saved or discarded?

**Comment by skejeton** [comment]
Currently the entity is added to the Object List immediately, the property window can be re-opened by opening the object in the object list. But it's a bit confusing since it doesn't point to the entity when you select it.

**Comment by vtereshkov** [comment]
Yes, I even have to switch between pages before I find the recently added entity.

**Comment by skejeton** [comment]
Fixed some of these:
- #47
- #48

**Comment by skejeton** [comment]
Closing because this seems to be already answered, but if you have more create a new issue.
