### ISSUE TITLE
More robust and configurable editor

### ISSUE THREAD

**Issue by Matoo125** [skejeton/education-tool#9]
The new editor will introduce transportation, new camera angles and environment options, as well as portals.

@skejeton please keep this issue updated, as you make improvements or change the scope.

**Comment by skejeton** [comment]
Added [low-priority], for now an internal hacky editor would be just fine.

**Comment by skejeton** [comment]
Not yet... But I'll close this issue because it's very vague. Instead we'll create issues as problems arise.
